# Generated by Django 4.2.8 on 2024-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0002_device_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_update",
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
