# Generated by Django 4.2.8 on 2024-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0004_alter_device_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
