# Generated by Django 4.2.8 on 2024-03-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0005_alter_device_last_update"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
