# Generated by Django 4.2.8 on 2024-04-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0008_alter_device_current_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit", name="number", field=models.IntegerField(default=0),
        ),
    ]
