# Generated by Django 4.2.8 on 2024-04-27 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0009_unit_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="api_key",
            field=models.CharField(default=uuid.uuid4, max_length=256, unique=True),
        ),
    ]
