# Generated by Django 4.2.8 on 2024-04-30 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0010_device_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(default=uuid.uuid4, max_length=256, unique=True),
                ),
            ],
        ),
    ]
