# Generated by Django 4.2.8 on 2024-05-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0011_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=9, null=True)),
                ("total_reading", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aquabill.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("month", models.CharField(max_length=9, null=True)),
                ("day", models.IntegerField(blank=True, null=True)),
                ("total_reading", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aquabill.device",
                    ),
                ),
            ],
        ),
    ]
