# Generated by Django 4.2.8 on 2024-05-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0012_monthlyarchive_dailyarchive"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
