# Generated by Django 4.2.8 on 2024-05-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0014_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyarchive",
            name="day",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="dailyarchive",
            name="total_reading",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="device",
            name="current_read",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="month_read",
            field=models.FloatField(default=0, null=True),
        ),
    ]
