# Generated by Django 4.2.8 on 2024-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0015_alter_dailyarchive_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device", name="last_update", field=models.DateTimeField(),
        ),
    ]
