# Generated by Django 4.2.8 on 2024-05-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0016_alter_device_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
