# Generated by Django 4.2.8 on 2024-05-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0017_alter_device_last_update"),
    ]

    operations = [
        migrations.DeleteModel(name="Proxy",),
    ]
