# Generated by Django 4.2.8 on 2024-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquabill", "0018_delete_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="quality_level",
            field=models.FloatField(default=0.4),
        ),
    ]
